import React, { useState } from 'react';
import axios from 'axios';

const Verify2FA = () => {
    const [username, setUsername] = useState('');
    const [token, setToken] = useState('');
    const [message, setMessage] = useState('');

    // Verify2FA.js
const handleVerify2FA = async (e) => {
    e.preventDefault();
    try {
        const response = await axios.post('http://localhost:3000/api/verify-2fa', {
            username,
            token,
        });
        setMessage(response.data.message);
    } catch (error) {
        console.error('Verification Error:', error.response?.data || error.message);
        setMessage(error.response?.data?.message || 'Failed to verify 2FA');
    }
};



    return (
        <div>
            <h2>Verify 2FA</h2>
            <p>Enter the OTP generated by your authenticator app.</p>
            <form onSubmit={handleVerify2FA}>
                <input
                    type="text"
                    placeholder="Username"
                    value={username}
                    onChange={(e) => setUsername(e.target.value)}
                    required
                />
                <input
                    type="text"
                    placeholder="2FA Token"
                    value={token}
                    onChange={(e) => setToken(e.target.value)}
                    required
                />
                <button type="submit">Verify 2FA</button>
            </form>
            <p>{message}</p>
        </div>
    );
};

export default Verify2FA;
